name: scan-gitleaks
description: Run Gitleaks secrets scan and export JSON results.

inputs:
  source:
    description: Repository directory to scan.
    required: false
    default: .
  config-file:
    description: Gitleaks config file path.
    required: false
    default: policies/secrets/gitleaks.toml
  output-file:
    description: Output file path for Gitleaks JSON results.
    required: false
    default: results/gitleaks.json
  gitleaks-version:
    description: Pinned Gitleaks version.
    required: false
    default: 8.21.2

runs:
  using: composite
  steps:
    - name: Install Gitleaks
      shell: bash
      run: |
        set -euo pipefail
        VERSION="${{ inputs.gitleaks-version }}"
        TMP_ARCHIVE="/tmp/gitleaks.tar.gz"
        curl -sfL "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz" -o "$TMP_ARCHIVE"
        tar -xzf "$TMP_ARCHIVE" -C /tmp
        sudo install -m 0755 /tmp/gitleaks /usr/local/bin/gitleaks
        gitleaks version

    - name: Run Gitleaks scan
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$(dirname "${{ inputs.output-file }}")"
        gitleaks detect \
          --source "${{ inputs.source }}" \
          --report-format json \
          --report-path "${{ inputs.output-file }}" \
          --config "${{ inputs.config-file }}" \
          --redact \
          --verbose

    - name: Confirm output
      shell: bash
      run: |
        set -euo pipefail
        test -f "${{ inputs.output-file }}"
        echo "Gitleaks results written to ${{ inputs.output-file }}"
